// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: from_buoy/self_test/v1/self_test.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "from_buoy.self_test.v1";

/** Identity and manifest of the system. Transferred on boot or command */
export interface SelfTest {
  /** Overall success of the test */
  success?:
    | boolean
    | undefined;
  /** The test rapport (JSON encoded) */
  rapport?: string | undefined;
}

function createBaseSelfTest(): SelfTest {
  return { success: undefined, rapport: undefined };
}

export const SelfTest: MessageFns<SelfTest> = {
  encode(message: SelfTest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== undefined) {
      writer.uint32(8).bool(message.success);
    }
    if (message.rapport !== undefined) {
      writer.uint32(18).string(message.rapport);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SelfTest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSelfTest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rapport = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SelfTest {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : undefined,
      rapport: isSet(object.rapport) ? globalThis.String(object.rapport) : undefined,
    };
  },

  toJSON(message: SelfTest): unknown {
    const obj: any = {};
    if (message.success !== undefined) {
      obj.success = message.success;
    }
    if (message.rapport !== undefined) {
      obj.rapport = message.rapport;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SelfTest>, I>>(base?: I): SelfTest {
    return SelfTest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SelfTest>, I>>(object: I): SelfTest {
    const message = createBaseSelfTest();
    message.success = object.success ?? undefined;
    message.rapport = object.rapport ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
