/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_FROM_BUOY_GNSS_V1_FROM_BUOY_GNSS_V1_GNSS_PB_H_INCLUDED
#define PB_FROM_BUOY_GNSS_V1_FROM_BUOY_GNSS_V1_GNSS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Latitude and longitude with some quality indicators */
typedef struct _from_buoy_gnss_v1_Location {
    /* Recorded at UTC Seconds since 2025-01-01T00:00:00Z */
    bool has_seconds2025;
    uint32_t seconds2025;
    /* Latitude in degrees */
    bool has_latitude;
    double latitude;
    /* Longitude in degrees */
    bool has_longitude;
    double longitude;
    /* GNSS quality indicator */
    bool has_quality;
    uint32_t quality;
    /* Number of satellites used */
    bool has_number_of_satellites;
    uint32_t number_of_satellites;
} from_buoy_gnss_v1_Location;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define from_buoy_gnss_v1_Location_init_default  {false, 0, false, 0, false, 0, false, 0, false, 0}
#define from_buoy_gnss_v1_Location_init_zero     {false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define from_buoy_gnss_v1_Location_seconds2025_tag 1
#define from_buoy_gnss_v1_Location_latitude_tag  2
#define from_buoy_gnss_v1_Location_longitude_tag 3
#define from_buoy_gnss_v1_Location_quality_tag   4
#define from_buoy_gnss_v1_Location_number_of_satellites_tag 5

/* Struct field encoding specification for nanopb */
#define from_buoy_gnss_v1_Location_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   seconds2025,       1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   latitude,          2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   longitude,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   quality,           4) \
X(a, STATIC,   OPTIONAL, UINT32,   number_of_satellites,   5)
#define from_buoy_gnss_v1_Location_CALLBACK NULL
#define from_buoy_gnss_v1_Location_DEFAULT NULL

extern const pb_msgdesc_t from_buoy_gnss_v1_Location_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define from_buoy_gnss_v1_Location_fields &from_buoy_gnss_v1_Location_msg

/* Maximum encoded size of messages (where known) */
#define FROM_BUOY_GNSS_V1_FROM_BUOY_GNSS_V1_GNSS_PB_H_MAX_SIZE from_buoy_gnss_v1_Location_size
#define from_buoy_gnss_v1_Location_size          36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
