/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_FROM_BUOY_LOG_V1_FROM_BUOY_LOG_V1_LOG_PB_H_INCLUDED
#define PB_FROM_BUOY_LOG_V1_FROM_BUOY_LOG_V1_LOG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* The level or importance of the log message */
typedef enum _from_buoy_log_v1_Level {
    /* Not specified log level */
    from_buoy_log_v1_Level_LEVEL_UNSPECIFIED = 0,
    /* Debug log level */
    from_buoy_log_v1_Level_LEVEL_DEBUG = 1,
    /* Informational log level */
    from_buoy_log_v1_Level_LEVEL_INFO = 2,
    /* Warning log level */
    from_buoy_log_v1_Level_LEVEL_WARNING = 3,
    /* Error log level */
    from_buoy_log_v1_Level_LEVEL_ERROR = 4,
    /* Critical log level, a non-recoverable error */
    from_buoy_log_v1_Level_LEVEL_CRITICAL = 5
} from_buoy_log_v1_Level;

/* In which part did error occur? */
typedef enum _from_buoy_log_v1_Subsystem {
    /* Unknown or not set */
    from_buoy_log_v1_Subsystem_SUBSYSTEM_UNSPECIFIED = 0,
    /* Main CPU */
    from_buoy_log_v1_Subsystem_SUBSYSTEM_CPU = 1,
    /* Communications */
    from_buoy_log_v1_Subsystem_SUBSYSTEM_COMMS = 2,
    /* AD2CP */
    from_buoy_log_v1_Subsystem_SUBSYSTEM_AD2CP = 3,
    /* GNSS */
    from_buoy_log_v1_Subsystem_SUBSYSTEM_GNSS = 4
} from_buoy_log_v1_Subsystem;

/* Struct definitions */
/* Detailed log information where in code */
typedef struct _from_buoy_log_v1_Detailed {
    /* Detailed log message */
    pb_callback_t filename;
    /* Function name */
    pb_callback_t function;
    /* Line number */
    bool has_line;
    uint32_t line;
    /* Column number */
    bool has_column;
    uint32_t column;
} from_buoy_log_v1_Detailed;

/* This is the log message */
typedef struct _from_buoy_log_v1_Entry {
    /* Recorded at UTC Seconds since 2025-01-01T00:00:00Z */
    bool has_seconds_2025;
    uint32_t seconds_2025;
    /* Log level */
    bool has_level;
    from_buoy_log_v1_Level level;
    /* Subsystem that generated the log */
    bool has_subsystem;
    from_buoy_log_v1_Subsystem subsystem;
    /* Log message */
    pb_callback_t message;
    /* Detailed log information */
    bool has_detailed;
    from_buoy_log_v1_Detailed detailed;
} from_buoy_log_v1_Entry;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _from_buoy_log_v1_Level_MIN from_buoy_log_v1_Level_LEVEL_UNSPECIFIED
#define _from_buoy_log_v1_Level_MAX from_buoy_log_v1_Level_LEVEL_CRITICAL
#define _from_buoy_log_v1_Level_ARRAYSIZE ((from_buoy_log_v1_Level)(from_buoy_log_v1_Level_LEVEL_CRITICAL+1))

#define _from_buoy_log_v1_Subsystem_MIN from_buoy_log_v1_Subsystem_SUBSYSTEM_UNSPECIFIED
#define _from_buoy_log_v1_Subsystem_MAX from_buoy_log_v1_Subsystem_SUBSYSTEM_GNSS
#define _from_buoy_log_v1_Subsystem_ARRAYSIZE ((from_buoy_log_v1_Subsystem)(from_buoy_log_v1_Subsystem_SUBSYSTEM_GNSS+1))


#define from_buoy_log_v1_Entry_level_ENUMTYPE from_buoy_log_v1_Level
#define from_buoy_log_v1_Entry_subsystem_ENUMTYPE from_buoy_log_v1_Subsystem


/* Initializer values for message structs */
#define from_buoy_log_v1_Detailed_init_default   {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define from_buoy_log_v1_Entry_init_default      {false, 0, false, _from_buoy_log_v1_Level_MIN, false, _from_buoy_log_v1_Subsystem_MIN, {{NULL}, NULL}, false, from_buoy_log_v1_Detailed_init_default}
#define from_buoy_log_v1_Detailed_init_zero      {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define from_buoy_log_v1_Entry_init_zero         {false, 0, false, _from_buoy_log_v1_Level_MIN, false, _from_buoy_log_v1_Subsystem_MIN, {{NULL}, NULL}, false, from_buoy_log_v1_Detailed_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define from_buoy_log_v1_Detailed_filename_tag   1
#define from_buoy_log_v1_Detailed_function_tag   2
#define from_buoy_log_v1_Detailed_line_tag       3
#define from_buoy_log_v1_Detailed_column_tag     4
#define from_buoy_log_v1_Entry_seconds_2025_tag  1
#define from_buoy_log_v1_Entry_level_tag         2
#define from_buoy_log_v1_Entry_subsystem_tag     3
#define from_buoy_log_v1_Entry_message_tag       4
#define from_buoy_log_v1_Entry_detailed_tag      5

/* Struct field encoding specification for nanopb */
#define from_buoy_log_v1_Detailed_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   filename,          1) \
X(a, CALLBACK, OPTIONAL, STRING,   function,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   line,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   column,            4)
#define from_buoy_log_v1_Detailed_CALLBACK pb_default_field_callback
#define from_buoy_log_v1_Detailed_DEFAULT NULL

#define from_buoy_log_v1_Entry_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   seconds_2025,      1) \
X(a, STATIC,   OPTIONAL, UENUM,    level,             2) \
X(a, STATIC,   OPTIONAL, UENUM,    subsystem,         3) \
X(a, CALLBACK, OPTIONAL, STRING,   message,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  detailed,          5)
#define from_buoy_log_v1_Entry_CALLBACK pb_default_field_callback
#define from_buoy_log_v1_Entry_DEFAULT NULL
#define from_buoy_log_v1_Entry_detailed_MSGTYPE from_buoy_log_v1_Detailed

extern const pb_msgdesc_t from_buoy_log_v1_Detailed_msg;
extern const pb_msgdesc_t from_buoy_log_v1_Entry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define from_buoy_log_v1_Detailed_fields &from_buoy_log_v1_Detailed_msg
#define from_buoy_log_v1_Entry_fields &from_buoy_log_v1_Entry_msg

/* Maximum encoded size of messages (where known) */
/* from_buoy_log_v1_Detailed_size depends on runtime parameters */
/* from_buoy_log_v1_Entry_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
