/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "from_buoy/log/v1/log.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(from_buoy_log_v1_Detailed, from_buoy_log_v1_Detailed, AUTO)


PB_BIND(from_buoy_log_v1_Entry, from_buoy_log_v1_Entry, AUTO)







