/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_FROM_BUOY_WAVE_V1_FROM_BUOY_WAVE_V1_WAVE_PB_H_INCLUDED
#define PB_FROM_BUOY_WAVE_V1_FROM_BUOY_WAVE_V1_WAVE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* This a wave profile (measured by GNSS) */
typedef struct _from_buoy_wave_v1_Profile {
    /* Recorded at UTC Seconds since 2025-01-01T00:00:00Z */
    bool has_seconds_2025;
    uint32_t seconds_2025;
    /* Significant wave height max 100 parts */
    bool has_significant_wave_height_max_100_parts;
    uint32_t significant_wave_height_max_100_parts;
    /* Mean wave height max 100 parts */
    bool has_mean_wave_height_100_parts;
    uint32_t mean_wave_height_100_parts;
    /* Mean wave height (BF) max 100 parts */
    bool has_mean_wave_height_bf_100_parts;
    uint32_t mean_wave_height_bf_100_parts;
    /* Mean wave height (HF) max 100 parts */
    bool has_mean_wave_height_hf_100_parts;
    uint32_t mean_wave_height_hf_100_parts;
    /* Peak wave period 100 parts */
    bool has_peak_wave_period_100_parts;
    uint32_t peak_wave_period_100_parts;
    /* Mean wave period 100 parts */
    bool has_mean_wave_period_100_parts;
    uint32_t mean_wave_period_100_parts;
    /* Peak wave period (BF) 10 parts */
    bool has_peak_wave_period_bf_10_parts;
    uint32_t peak_wave_period_bf_10_parts;
    /* Peak wave period (HF) 10 parts */
    bool has_peak_wave_period_hf_10_parts;
    uint32_t peak_wave_period_hf_10_parts;
    /* Zero crossing period 100 parts */
    bool has_zero_crossing_period_100_parts;
    uint32_t zero_crossing_period_100_parts;
    /* Number of waves detected */
    bool has_number_of_waves;
    uint32_t number_of_waves;
    /* Directional spread 10 parts */
    bool has_directional_spread_10_parts;
    int32_t directional_spread_10_parts;
    /* Maximum period 100 parts */
    bool has_maximum_period_100_parts;
    uint32_t maximum_period_100_parts;
    /* Time at Hmax 10 parts */
    bool has_time_at_hmax_10_parts;
    uint32_t time_at_hmax_10_parts;
    /* Height of highest third 100 parts */
    bool has_height_of_highest_third_100_parts;
    uint32_t height_of_highest_third_100_parts;
    /* Mean period of highest third 100 parts */
    bool has_mean_period_of_highest_third_100_parts;
    uint32_t mean_period_of_highest_third_100_parts;
    /* Mean direction Tp 10 parts */
    bool has_tp_mean_direction_10_parts;
    int32_t tp_mean_direction_10_parts;
    /* Mean direction BF Tp 10 parts */
    bool has_tp_direction_bf_10_parts;
    int32_t tp_direction_bf_10_parts;
    /* Mean direction HF Tp 10 parts */
    bool has_tp_direction_hf_10_parts;
    int32_t tp_direction_hf_10_parts;
    /* Mean T01 period 10 parts */
    bool has_t01_mean_period_10_parts;
    uint32_t t01_mean_period_10_parts;
    /* Mean period T02 BF 10 parts */
    bool has_t02_mean_period_bf_10_parts;
    uint32_t t02_mean_period_bf_10_parts;
    /* Mean period T02 HF 10 parts */
    bool has_t02_mean_period_hf_10_parts;
    uint32_t t02_mean_period_hf_10_parts;
    /* Direction T02 BF 10 parts */
    bool has_t02_direction_bf_10_parts;
    int32_t t02_direction_bf_10_parts;
    /* Direction T02 HF 10 parts */
    bool has_t02_direction_hf_10_parts;
    int32_t t02_direction_hf_10_parts;
    /* Mean direction T02 10 parts */
    bool has_t02_mean_direction_10_parts;
    int32_t t02_mean_direction_10_parts;
    /* Raw GNSS data, used when high bandwidth is required link / Cellular */
    pb_callback_t raw_gnss;
} from_buoy_wave_v1_Profile;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define from_buoy_wave_v1_Profile_init_default   {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define from_buoy_wave_v1_Profile_init_zero      {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define from_buoy_wave_v1_Profile_seconds_2025_tag 1
#define from_buoy_wave_v1_Profile_significant_wave_height_max_100_parts_tag 2
#define from_buoy_wave_v1_Profile_mean_wave_height_100_parts_tag 3
#define from_buoy_wave_v1_Profile_mean_wave_height_bf_100_parts_tag 4
#define from_buoy_wave_v1_Profile_mean_wave_height_hf_100_parts_tag 5
#define from_buoy_wave_v1_Profile_peak_wave_period_100_parts_tag 6
#define from_buoy_wave_v1_Profile_mean_wave_period_100_parts_tag 7
#define from_buoy_wave_v1_Profile_peak_wave_period_bf_10_parts_tag 8
#define from_buoy_wave_v1_Profile_peak_wave_period_hf_10_parts_tag 9
#define from_buoy_wave_v1_Profile_zero_crossing_period_100_parts_tag 10
#define from_buoy_wave_v1_Profile_number_of_waves_tag 11
#define from_buoy_wave_v1_Profile_directional_spread_10_parts_tag 12
#define from_buoy_wave_v1_Profile_maximum_period_100_parts_tag 13
#define from_buoy_wave_v1_Profile_time_at_hmax_10_parts_tag 14
#define from_buoy_wave_v1_Profile_height_of_highest_third_100_parts_tag 15
#define from_buoy_wave_v1_Profile_mean_period_of_highest_third_100_parts_tag 16
#define from_buoy_wave_v1_Profile_tp_mean_direction_10_parts_tag 17
#define from_buoy_wave_v1_Profile_tp_direction_bf_10_parts_tag 18
#define from_buoy_wave_v1_Profile_tp_direction_hf_10_parts_tag 19
#define from_buoy_wave_v1_Profile_t01_mean_period_10_parts_tag 20
#define from_buoy_wave_v1_Profile_t02_mean_period_bf_10_parts_tag 21
#define from_buoy_wave_v1_Profile_t02_mean_period_hf_10_parts_tag 22
#define from_buoy_wave_v1_Profile_t02_direction_bf_10_parts_tag 23
#define from_buoy_wave_v1_Profile_t02_direction_hf_10_parts_tag 24
#define from_buoy_wave_v1_Profile_t02_mean_direction_10_parts_tag 25
#define from_buoy_wave_v1_Profile_raw_gnss_tag   26

/* Struct field encoding specification for nanopb */
#define from_buoy_wave_v1_Profile_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   seconds_2025,      1) \
X(a, STATIC,   OPTIONAL, UINT32,   significant_wave_height_max_100_parts,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   mean_wave_height_100_parts,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   mean_wave_height_bf_100_parts,   4) \
X(a, STATIC,   OPTIONAL, UINT32,   mean_wave_height_hf_100_parts,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   peak_wave_period_100_parts,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   mean_wave_period_100_parts,   7) \
X(a, STATIC,   OPTIONAL, UINT32,   peak_wave_period_bf_10_parts,   8) \
X(a, STATIC,   OPTIONAL, UINT32,   peak_wave_period_hf_10_parts,   9) \
X(a, STATIC,   OPTIONAL, UINT32,   zero_crossing_period_100_parts,  10) \
X(a, STATIC,   OPTIONAL, UINT32,   number_of_waves,  11) \
X(a, STATIC,   OPTIONAL, SINT32,   directional_spread_10_parts,  12) \
X(a, STATIC,   OPTIONAL, UINT32,   maximum_period_100_parts,  13) \
X(a, STATIC,   OPTIONAL, UINT32,   time_at_hmax_10_parts,  14) \
X(a, STATIC,   OPTIONAL, UINT32,   height_of_highest_third_100_parts,  15) \
X(a, STATIC,   OPTIONAL, UINT32,   mean_period_of_highest_third_100_parts,  16) \
X(a, STATIC,   OPTIONAL, SINT32,   tp_mean_direction_10_parts,  17) \
X(a, STATIC,   OPTIONAL, SINT32,   tp_direction_bf_10_parts,  18) \
X(a, STATIC,   OPTIONAL, SINT32,   tp_direction_hf_10_parts,  19) \
X(a, STATIC,   OPTIONAL, UINT32,   t01_mean_period_10_parts,  20) \
X(a, STATIC,   OPTIONAL, UINT32,   t02_mean_period_bf_10_parts,  21) \
X(a, STATIC,   OPTIONAL, UINT32,   t02_mean_period_hf_10_parts,  22) \
X(a, STATIC,   OPTIONAL, SINT32,   t02_direction_bf_10_parts,  23) \
X(a, STATIC,   OPTIONAL, SINT32,   t02_direction_hf_10_parts,  24) \
X(a, STATIC,   OPTIONAL, SINT32,   t02_mean_direction_10_parts,  25) \
X(a, CALLBACK, OPTIONAL, BYTES,    raw_gnss,         26)
#define from_buoy_wave_v1_Profile_CALLBACK pb_default_field_callback
#define from_buoy_wave_v1_Profile_DEFAULT NULL

extern const pb_msgdesc_t from_buoy_wave_v1_Profile_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define from_buoy_wave_v1_Profile_fields &from_buoy_wave_v1_Profile_msg

/* Maximum encoded size of messages (where known) */
/* from_buoy_wave_v1_Profile_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
