/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_FROM_BUOY_SELF_TEST_V1_FROM_BUOY_SELF_TEST_V1_SELF_TEST_PB_H_INCLUDED
#define PB_FROM_BUOY_SELF_TEST_V1_FROM_BUOY_SELF_TEST_V1_SELF_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Identity and manifest of the system. Transferred on boot or command */
typedef struct _from_buoy_self_test_v1_SelfTest {
    /* Overall success of the test */
    bool has_success;
    bool success;
    /* The test rapport (JSON encoded) */
    pb_callback_t rapport;
} from_buoy_self_test_v1_SelfTest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define from_buoy_self_test_v1_SelfTest_init_default {false, 0, {{NULL}, NULL}}
#define from_buoy_self_test_v1_SelfTest_init_zero {false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define from_buoy_self_test_v1_SelfTest_success_tag 1
#define from_buoy_self_test_v1_SelfTest_rapport_tag 2

/* Struct field encoding specification for nanopb */
#define from_buoy_self_test_v1_SelfTest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     success,           1) \
X(a, CALLBACK, OPTIONAL, STRING,   rapport,           2)
#define from_buoy_self_test_v1_SelfTest_CALLBACK pb_default_field_callback
#define from_buoy_self_test_v1_SelfTest_DEFAULT NULL

extern const pb_msgdesc_t from_buoy_self_test_v1_SelfTest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define from_buoy_self_test_v1_SelfTest_fields &from_buoy_self_test_v1_SelfTest_msg

/* Maximum encoded size of messages (where known) */
/* from_buoy_self_test_v1_SelfTest_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
