/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "from_buoy/v1/from_buoy.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(from_buoy_v1_MultiMessage, from_buoy_v1_MultiMessage, AUTO)


PB_BIND(from_buoy_v1_SensorRecord, from_buoy_v1_SensorRecord, AUTO)


PB_BIND(from_buoy_v1_FromBuoy, from_buoy_v1_FromBuoy, 2)



