/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_FROM_BUOY_AD2CP_V1_FROM_BUOY_AD2CP_V1_AD2CP_PB_H_INCLUDED
#define PB_FROM_BUOY_AD2CP_V1_FROM_BUOY_AD2CP_V1_AD2CP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Values are stored in Delta Zig-Zag coding relative to previous cell */
typedef struct _from_buoy_ad2cp_v1_Cell {
    /* Direction of current in tenths of degrees */
    bool has_direction_10parts;
    int32_t direction_10parts;
    /* Speed of current in hundredths of meters per second */
    bool has_velocity_100parts;
    int32_t velocity_100parts;
    /* Amplitude / Strength of signal in tenths of dB */
    bool has_amplitude_10parts;
    int32_t amplitude_10parts;
} from_buoy_ad2cp_v1_Cell;

/* AD2CP with sensor values and current cell profile */
typedef struct _from_buoy_ad2cp_v1_Profile {
    /* Recorded at UTC Seconds since 2025-01-01T00:00:00Z */
    bool has_seconds_2025;
    uint32_t seconds_2025;
    /* Temperature in hundredths of degrees */
    bool has_temperature_100parts;
    uint32_t temperature_100parts;
    /* Pressure in hundredths of dBar */
    bool has_pressure_100parts;
    uint32_t pressure_100parts;
    /* Pitch in tenths of degrees */
    bool has_pitch_10parts;
    int32_t pitch_10parts;
    /* Roll in tenths of degrees */
    bool has_roll_10parts;
    int32_t roll_10parts;
    /* Velocity scale in hundredths */
    bool has_velocity_scale;
    int32_t velocity_scale;
    /* Cells in the profile */
    pb_callback_t cells;
    /* Raw AD2CP data, used when high bandwidth is required link / Cellular */
    pb_callback_t raw_ad2cp;
} from_buoy_ad2cp_v1_Profile;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define from_buoy_ad2cp_v1_Cell_init_default     {false, 0, false, 0, false, 0}
#define from_buoy_ad2cp_v1_Profile_init_default  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define from_buoy_ad2cp_v1_Cell_init_zero        {false, 0, false, 0, false, 0}
#define from_buoy_ad2cp_v1_Profile_init_zero     {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define from_buoy_ad2cp_v1_Cell_direction_10parts_tag 1
#define from_buoy_ad2cp_v1_Cell_velocity_100parts_tag 2
#define from_buoy_ad2cp_v1_Cell_amplitude_10parts_tag 3
#define from_buoy_ad2cp_v1_Profile_seconds_2025_tag 1
#define from_buoy_ad2cp_v1_Profile_temperature_100parts_tag 2
#define from_buoy_ad2cp_v1_Profile_pressure_100parts_tag 3
#define from_buoy_ad2cp_v1_Profile_pitch_10parts_tag 4
#define from_buoy_ad2cp_v1_Profile_roll_10parts_tag 5
#define from_buoy_ad2cp_v1_Profile_velocity_scale_tag 6
#define from_buoy_ad2cp_v1_Profile_cells_tag     7
#define from_buoy_ad2cp_v1_Profile_raw_ad2cp_tag 8

/* Struct field encoding specification for nanopb */
#define from_buoy_ad2cp_v1_Cell_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, SINT32,   direction_10parts,   1) \
X(a, STATIC,   OPTIONAL, SINT32,   velocity_100parts,   2) \
X(a, STATIC,   OPTIONAL, SINT32,   amplitude_10parts,   3)
#define from_buoy_ad2cp_v1_Cell_CALLBACK NULL
#define from_buoy_ad2cp_v1_Cell_DEFAULT NULL

#define from_buoy_ad2cp_v1_Profile_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   seconds_2025,      1) \
X(a, STATIC,   OPTIONAL, UINT32,   temperature_100parts,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   pressure_100parts,   3) \
X(a, STATIC,   OPTIONAL, SINT32,   pitch_10parts,     4) \
X(a, STATIC,   OPTIONAL, SINT32,   roll_10parts,      5) \
X(a, STATIC,   OPTIONAL, SINT32,   velocity_scale,    6) \
X(a, CALLBACK, REPEATED, MESSAGE,  cells,             7) \
X(a, CALLBACK, OPTIONAL, BYTES,    raw_ad2cp,         8)
#define from_buoy_ad2cp_v1_Profile_CALLBACK pb_default_field_callback
#define from_buoy_ad2cp_v1_Profile_DEFAULT NULL
#define from_buoy_ad2cp_v1_Profile_cells_MSGTYPE from_buoy_ad2cp_v1_Cell

extern const pb_msgdesc_t from_buoy_ad2cp_v1_Cell_msg;
extern const pb_msgdesc_t from_buoy_ad2cp_v1_Profile_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define from_buoy_ad2cp_v1_Cell_fields &from_buoy_ad2cp_v1_Cell_msg
#define from_buoy_ad2cp_v1_Profile_fields &from_buoy_ad2cp_v1_Profile_msg

/* Maximum encoded size of messages (where known) */
/* from_buoy_ad2cp_v1_Profile_size depends on runtime parameters */
#define FROM_BUOY_AD2CP_V1_FROM_BUOY_AD2CP_V1_AD2CP_PB_H_MAX_SIZE from_buoy_ad2cp_v1_Cell_size
#define from_buoy_ad2cp_v1_Cell_size             18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
