/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "from_buoy/ad2cp/v1/ad2cp.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(from_buoy_ad2cp_v1_Cell, from_buoy_ad2cp_v1_Cell, AUTO)


PB_BIND(from_buoy_ad2cp_v1_Profile, from_buoy_ad2cp_v1_Profile, AUTO)



