/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_DEBUG_V1_DEBUG_V1_DEBUG_PB_H_INCLUDED
#define PB_DEBUG_V1_DEBUG_V1_DEBUG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Debug message for testing GNSS and Iridium */
typedef struct _debug_v1_Debug {
    /* Message sent UTC Seconds since 2025-01-01T00:00:00Z */
    uint32_t seconds_2025;
    /* Iridium start TTS milliseconds */
    uint32_t iridium_start_tts;
    /* milliseconds */
    uint32_t iridium_prev_message_transfer_time;
    /* 0-5 bars */
    uint32_t iridium_signal_strength;
    /* milliseconds */
    uint32_t gnss_time_to_first_fix;
    /* number of satellites */
    uint32_t gnss_num_satellites;
    /* 0-5 bars */
    uint32_t gnss_signal_strengths;
    /* Latitude */
    double gnss_lat;
    /* Longitude */
    double gnss_lon;
    /* Altitude */
    double gnss_alt;
} debug_v1_Debug;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define debug_v1_Debug_init_default              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define debug_v1_Debug_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define debug_v1_Debug_seconds_2025_tag          1
#define debug_v1_Debug_iridium_start_tts_tag     2
#define debug_v1_Debug_iridium_prev_message_transfer_time_tag 3
#define debug_v1_Debug_iridium_signal_strength_tag 4
#define debug_v1_Debug_gnss_time_to_first_fix_tag 6
#define debug_v1_Debug_gnss_num_satellites_tag   7
#define debug_v1_Debug_gnss_signal_strengths_tag 8
#define debug_v1_Debug_gnss_lat_tag              9
#define debug_v1_Debug_gnss_lon_tag              10
#define debug_v1_Debug_gnss_alt_tag              11

/* Struct field encoding specification for nanopb */
#define debug_v1_Debug_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seconds_2025,      1) \
X(a, STATIC,   SINGULAR, UINT32,   iridium_start_tts,   2) \
X(a, STATIC,   SINGULAR, UINT32,   iridium_prev_message_transfer_time,   3) \
X(a, STATIC,   SINGULAR, UINT32,   iridium_signal_strength,   4) \
X(a, STATIC,   SINGULAR, UINT32,   gnss_time_to_first_fix,   6) \
X(a, STATIC,   SINGULAR, UINT32,   gnss_num_satellites,   7) \
X(a, STATIC,   SINGULAR, UINT32,   gnss_signal_strengths,   8) \
X(a, STATIC,   SINGULAR, DOUBLE,   gnss_lat,          9) \
X(a, STATIC,   SINGULAR, DOUBLE,   gnss_lon,         10) \
X(a, STATIC,   SINGULAR, DOUBLE,   gnss_alt,         11)
#define debug_v1_Debug_CALLBACK NULL
#define debug_v1_Debug_DEFAULT NULL

extern const pb_msgdesc_t debug_v1_Debug_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define debug_v1_Debug_fields &debug_v1_Debug_msg

/* Maximum encoded size of messages (where known) */
#define DEBUG_V1_DEBUG_V1_DEBUG_PB_H_MAX_SIZE    debug_v1_Debug_size
#define debug_v1_Debug_size                      69

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
