/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "from_buoy/manifest/v1/manifest.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(from_buoy_manifest_v1_Manifest, from_buoy_manifest_v1_Manifest, AUTO)









