/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "from_buoy/system/v1/system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(from_buoy_system_v1_Performance, from_buoy_system_v1_Performance, AUTO)





